# Generated by Django 4.2 on 2023-04-07 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_to_options_alter_machine_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user__groups__name': 'Клиент'}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='base.userprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipping_date',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='fail_date',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='recovery_date',
            field=models.DateField(verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='to',
            name='order_date',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='to',
            name='to_date',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
    ]
