# Generated by Django 4.2 on 2023-04-07 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_reclamation_fail_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='recovery',
            field=models.ForeignKey(limit_choices_to={'type_name': 'RE'}, on_delete=django.db.models.deletion.CASCADE, related_name='recovers', to='base.spravochnik', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='service',
            field=models.ForeignKey(limit_choices_to={'type_name': 'SR'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_reclams', to='base.spravochnik', verbose_name='Cервисная компания'),
        ),
    ]
