# Generated by Django 4.2 on 2023-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_machine_drive_num_alter_machine_eng_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spravochnik',
            name='description',
            field=models.CharField(default='Отсутствует', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=126, verbose_name='Описание'),
        ),
    ]
